### PR TITLE
Attempt to fix NSME in `AbstractToolProvider.findToolPath`

### LINKED ISSUE #73: Exception in agent logs if no tools installed on agent
```text
[2024-12-11 12:08:03,427]   WARN - ildServer.util.EventDispatcher - Error in event handler: Error calling method AgentLifeCycleListener.beforeAgentConfigurationLoaded for listener jetbrains.buildServer.rust.CargoToolProvider: java.util.NoSuchElementException
[2024-12-11 12:08:03,427]  DEBUG - ildServer.util.EventDispatcher - Error in event handler
Error calling method AgentLifeCycleListener.beforeAgentConfigurationLoaded for listener jetbrains.buildServer.rust.CargoToolProvider: java.util.NoSuchElementException
	at jetbrains.buildServer.util.EventDispatcher.invokeListeners(EventDispatcher.java:175)
	at jetbrains.buildServer.util.EventDispatcher.lambda$dispatch$0(EventDispatcher.java:134)
	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:76)
	at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:134)
	at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:82)
	at com.sun.proxy.$Proxy28.beforeAgentConfigurationLoaded(Unknown Source)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.init(BuildAgentImpl.java:896)
	at jetbrains.buildServer.agent.AgentMain2.startAgent(AgentMain2.java:222)
	at jetbrains.buildServer.agent.AgentMain2.main2(AgentMain2.java:98)
	at jetbrains.buildServer.agent.AgentMain2.main(AgentMain2.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at jetbrains.buildServer.agent.AgentMain.main(AgentMain.java:44)
Caused by: java.util.NoSuchElementException
	at jetbrains.buildServer.rust.AbstractToolProvider.findToolPath(AbstractToolProvider.kt:148)
	at jetbrains.buildServer.rust.AbstractToolProvider.beforeAgentConfigurationLoaded(AbstractToolProvider.kt:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at jetbrains.buildServer.util.EventDispatcher.invokeListeners(EventDispatcher.java:157)
	... 14 more
```

### PR DESCRIPTION
**Pull request by VladRassokhin**
Fixes #73

### CODE REVIEW

**Comment by VladRassokhin** [comment]
Actually fix in the second commit. The first one just slightly improves performance.

File: plugin-rust-agent/src/main/kotlin/jetbrains/buildServer/rust/AbstractToolProvider.kt [hunk 1]
```diff
@@ -24,7 +30,7 @@ abstract class AbstractToolProvider(
 ): AgentLifeCycleAdapter(), ToolProvider {
     private val LOG = Logger.getInstance(AbstractToolProvider::class.java.name)
     private val VERSION_PATTERN = Regex("^$configName[\\s-]([^\\s]+)", RegexOption.IGNORE_CASE)
-    private val PATH_PATTERN = Regex("^.*$configName(\\.(exe))?$", RegexOption.IGNORE_CASE)
+    private val FILE_NAME_PATTERN = Regex("^\\Q$configName\\E(\\.(exe))?$", RegexOption.IGNORE_CASE)
```
Comment (trespasserw) [inline plugin-rust-agent/src/main/kotlin/jetbrains/buildServer/rust/AbstractToolProvider.kt:33]: Why quote?

File: plugin-rust-agent/src/main/kotlin/jetbrains/buildServer/rust/AbstractToolProvider.kt [hunk 2]
```diff
@@ -78,14 +84,21 @@ abstract class AbstractToolProvider(
...
+                this.add(it + File.separatorChar + ".cargo" + File.separatorChar + "bin")
+            }
         }
 
-        return paths.mapNotNull { File(it).listFiles() }
-                .flatMap { it.map { it.absolutePath } }
-                .filter { PATH_PATTERN.matches(it) }
-                .mapNotNull {
+        return paths.map { File(it) }
+            .filter { it.exists() && it.isDirectory }
```
Comment (trespasserw) [inline plugin-rust-agent/src/main/kotlin/jetbrains/buildServer/rust/AbstractToolProvider.kt:96]: The filter is double unnecessary: is-directory implies existence, and list being not-null implies is-directory 🤷

File: plugin-rust-agent/src/main/kotlin/jetbrains/buildServer/rust/AbstractToolProvider.kt (hunk 1 above)
Comment (VladRassokhin) [reply plugin-rust-agent/src/main/kotlin/jetbrains/buildServer/rust/AbstractToolProvider.kt:33]: Just to make sure that `configName` doesn't contain regexp

File: plugin-rust-agent/src/main/kotlin/jetbrains/buildServer/rust/AbstractToolProvider.kt (hunk 2 above)
Comment (VladRassokhin) [reply plugin-rust-agent/src/main/kotlin/jetbrains/buildServer/rust/AbstractToolProvider.kt]: Replaced with `newDirectoryStream`

File: plugin-rust-agent/src/main/kotlin/jetbrains/buildServer/rust/AbstractToolProvider.kt (hunk 1 above)
Comment (VladRassokhin) [reply plugin-rust-agent/src/main/kotlin/jetbrains/buildServer/rust/AbstractToolProvider.kt]: Dropped regepx whatsoever. `lowercase`, `removeSuffix` and `equals` is enough

File: plugin-rust-agent/src/main/kotlin/jetbrains/buildServer/rust/AbstractToolProvider.kt [hunk 3]
```diff
@@ -78,24 +90,35 @@ abstract class AbstractToolProvider(
...
+                this.add(it + File.separatorChar + ".cargo" + File.separatorChar + "bin")
+            }
         }
 
-        return paths.mapNotNull { File(it).listFiles() }
-                .flatMap { it.map { it.absolutePath } }
-                .filter { PATH_PATTERN.matches(it) }
-                .mapNotNull {
+        return paths.map { Path.of(it) }
+            .filter { Files.isDirectory(it) }
```
Comment (trespasserw) [inline plugin-rust-agent/src/main/kotlin/jetbrains/buildServer/rust/AbstractToolProvider.kt:102]: Again, the filter is not needed, because by listing directories one has to handle errors anyway.

**Review by trespasserw — APPROVED** [review]
